
version: '3.8'

services:
  mariadb:
    image: mariadb:10.6
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: menudb
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  menu-service:
    build: ./menu-service
    container_name: menu-service
    ports:
      - "9001:9001"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/menudb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mariadb

volumes:
  mariadb_data:
